# Generated by Django 4.1.1 on 2022-09-17 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_folder_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='primary',
            field=models.BooleanField(default=False),
        ),
    ]
