# Generated by Django 4.1.1 on 2022-09-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_folder_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='primary',
        ),
    ]
