# Generated by Django 4.1.1 on 2022-09-24 11:15

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_folder_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='source',
            field=models.FileField(upload_to=base.models.File.get_user_folder, verbose_name='files/'),
        ),
    ]
