# Generated by Django 4.1.1 on 2022-09-24 15:16

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_file_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='source',
            field=models.FileField(upload_to=base.models.File.get_user_folder),
        ),
    ]
