# Generated by Django 4.1.1 on 2022-09-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_file_deleted_remove_folder_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='name',
            field=models.CharField(default='name', max_length=255, null=True),
        ),
    ]
